### ISSUE TITLE
Feature Idea/request: Write config to file

### ISSUE THREAD

**Issue by n1ru4l** [traefik/paerser#1]
A nice addition to this library would be the possibility of dumping a config object into a file as `JSON`/`YAML`/`TOML`. Is this something you might wanna consider?

That could also be a prerequisite for solving: https://github.com/traefik/traefik/issues/4174 (have one traefik instance that writes the config file and another for reading the config file in order to avoid docker socket exposure).

**Comment by ldez** [comment]
Hello,

To dump a configuration struct into a file, you just have to use the "standard" marshaller related to the format.

This library doesn't need to do that.
