### ISSUE TITLE
Unsupported field will stops loading configures

### ISSUE THREAD

**Issue by letian0805** [traefik/paerser#2]
See https://github.com/traefik/traefik/issues/7417

**Comment by ldez** [comment]
Hello, it's the expected behavior.

**Comment by letian0805** [comment]
> Hello, it's the expected behavior.

I created a pull request to fix it.
Let the caller to handle error.

**Comment by ldez** [comment]
The current behavior is the expected behavior in Traefik. I invite you to explain your use case in traefik/traefik#7417
